### ISSUE TITLE
Unable to view block details

### ISSUE THREAD

**Issue by Kuzirashi** [Magickbase/blockscan#70]
*Describe your issue here.*

When trying to visit example URL: https://khalani-axon-explorer-staging.digipnyx.org/block/155210/transactions the explorer returns 500 error:
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/4950658/229398630-977e4101-1fb0-4dda-a03a-5af9220fec06.png">

And in logs we can see:
```
Request: GET /block/155210/transactions
** (exit) an exception was raised:
** (FunctionClauseError) no function clause matching in Decimal.to_integer/1
(decimal 2.0.0) lib/decimal.ex:1322: Decimal.to_integer(nil)
(block_scout_web 5.1.1) lib/block_scout_web/templates/block/overview.html.eex:171: BlockScoutWeb.BlockView."overview.html"/1
(block_scout_web 5.1.1) lib/block_scout_web/templates/block_transaction/index.html.eex:3: BlockScoutWeb.BlockTransactionView."index.html"/1
(phoenix 1.5.13) lib/phoenix/view.ex:310: Phoenix.View.render_within/3
(phoenix 1.5.13) lib/phoenix/view.ex:472: Phoenix.View.render_to_iodata/3
(phoenix 1.5.13) lib/phoenix/controller.ex:777: Phoenix.Controller.render_and_send/4	blockscan
(block_scout_web 5.1.1) lib/block_scout_web/controllers/block_transaction_controller.ex:1: BlockScoutWeb.BlockTransactionController.action/2	blockscan
(block_scout_web 5.1.1) lib/block_scout_web/controllers/block_transaction_controller.ex:1: BlockScoutWeb.BlockTransactionController.phoenix_controller_pipeline/2
```

Maybe we're running too old Axon version, but I'm not sure how to debug this and what value could be a problem. It seems to complain about null value in the block details.

### Environment

Magickbase/blockscan: latest version
Axon: https://github.com/axonweb3/axon/tree/556950b37c0f9ccde00bb689cc4b98dc10556620 (October 2022 version)

### Steps to reproduce

eg. go to all blocks and then click to view block details

### Expected behaviour

Block details shown

### Actual behaviour

500 error

---

cc @Naupio

**Comment by Kuzirashi** [comment]
I think error is due to totalDifficulty being returned as null in Axon from October 2022. It was fixed in December 2022: https://github.com/axonweb3/axon/pull/888/files

Closing this issue.
